base_config: rcf_stage1.yaml
batch_size: 1
workers: 6

disable_wandb: true
# This is to allow existing saved dir
allow_overwriting_checkpoints_dir: true

data_path: ./data/data_vdv

checkpoints_dir: saved/saved_rcf_stage1
pretrained_model: saved/saved_rcf_stage1/epoch=22-step=13225.ckpt
object_channel: 0

# generate the blurred image is different from the simply test
test_dataset_kwargs:
  frame_num: 2
  load_flow: true

# In validation, it's save_eval
saved_eval_dir_name: saved_eval_test
saved_eval_export_dir_name: saved_eval_export

eval_pos_th: -1
eval_save: true
# export depends on save
eval_export: true
export_all_seg: true
