base_config: rcf_stage1_num3.yaml
batch_size: 1
workers: 6

disable_wandb: true
# This is to allow existing saved dir
allow_overwriting_checkpoints_dir: true

data_path: ./data/data_vdv2

checkpoints_dir: saved/saved_rcf_vdv2_stage1_synetic
pretrained_model: saved/saved_rcf_vdv2_stage1_num3/epoch=12-step=5824.ckpt
object_channel: 2

# generate the blurred image is different from the simply test
test_dataset_kwargs:
  frame_num: 2
  load_flow: true
  flow_suffix: "_NewCT"


# In validation, it's save_eval
saved_eval_dir_name: saved_eval_test
saved_eval_export_dir_name: saved_eval_export
saved_reblur_dir_name: saved_reblur

eval_pos_th: -1
eval_save: true
# export depends on save
eval_export: true
export_all_seg: true
