base_config: amd.yaml
batch_size: 1
workers: 6

disable_wandb: true
# This is to allow existing saved dir
allow_overwriting_checkpoints_dir: true
test_data_path: ./data/data_vdv

checkpoints_dir: saved/saved_amd
pretrained_model: saved/saved_amd/epoch=96-step=26093.ckpt

# Please set the object channel before evaluation
object_channel: 3

test_dataset_kwargs:
  split: val.txt

eval_pos_th: 0.35
eval_save: true
# export depends on save
eval_export: true
export_all_seg: false
