base_config: rcf_stage1.yaml
batch_size: 2
workers: 6

disable_wandb: true
# This is to allow existing saved dir
allow_overwriting_checkpoints_dir: true

data_path: ./data/data_vdv

checkpoints_dir: saved/saved_rcf_vdv_stage1
pretrained_model: saved/saved_rcf_vdv_stage1/epoch=26-step=5184.ckpt
object_channel: 0

# In validation, it's save_eval
saved_eval_dir_name: saved_eval_test
saved_eval_export_dir_name: saved_eval_export

eval_pos_th: -1
eval_save: true
# export depends on save
eval_export: true
export_all_seg: true
